statement_position:
  statement_mode: uncuddled_else

opt_in_rules:
- closure_spacing
- empty_count
- explicit_init
- overridden_super_call
- vertical_whitespace
disabled_rules:
- identifier_name
- line_length
- trailing_whitespace
- nesting
excluded:
- Pods
- R.generated.swift
- "*.playground"
