language: swift
os: osx
osx_image: xcode9.3
cache:
  directories:
  - Carthage
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Down.xcodeproj
  - SCHEME=Down
  - CC_TEST_REPORTER_ID=4074485b984af5323f0806408b43441628bc6f72f523b89c5338f87ae807820a
  matrix:
    - DESTINATION="OS=11.3,name=iPhone X"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - whoami
before_install:
  - gem install activesupport -N
  - gem install slather --no-rdoc
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds --verbose
script:
  - set -o pipefail
  - xcodebuild clean test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty
after_script:
  - slather
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT