language: swift
os: osx
osx_image: xcode10.2
cache:
  directories:
  - Pods
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - PROJECT=Down.xcworkspace
  - SCHEME=Down
  - CC_TEST_REPORTER_ID=4074485b984af5323f0806408b43441628bc6f72f523b89c5338f87ae807820a
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone XS"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - whoami
before_install:
  - pod install --repo-update
script:
  - xcodebuild test -workspace Down.xcworkspace -scheme "Down" -sdk iphonesimulator
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
