version: 2
jobs:
  build:
    macos:
      xcode: "10.2.1"

    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and run tests
          command: fastlane test
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs