fastlane_version "1.99.0"
default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Crashlytics"
  lane :beta do
    #gym(scheme: 'Down', configuration: 'Release')
    increment_build_number
  end

end
