statement_position:
  statement_mode: uncuddled_else
disabled_rules:
- trailing_whitespace
- todo
- line_length
- force_cast
excluded:
- Down/Dependencies
- R.generated.swift
- DownKit/Dependencies
- fastlane